from fastapi import APIRouter, Depends, Query
from datetime import datetime, timezone
from apps.backend.core.security import get_current_user, UserContext
from .schemas import GeneratedCode

router = APIRouter(prefix="/projects/{project_id}/code", tags=["codegen"])


@router.get("", response_model=GeneratedCode)
async def get_code(
    project_id: str,
    platform: str = Query("esp32", description="'arduino' or 'esp32'"),
    current_user: UserContext = Depends(get_current_user),
):
    """Retrieves generated firmware code for the circuit."""
    now = datetime.now(timezone.utc).isoformat()
    return GeneratedCode(
        platform=platform,
        source_code="// Generated by Eureka AI\nvoid setup() {\n  Serial.begin(115200);\n}\nvoid loop() {\n}\n",
        required_libraries=[],
        is_stale=False,
        generated_at=now,
    )
